[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_IGNORE_TYPESCRIPT_ERRORS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"